#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Complete
        '--frog'    => ['ribbit','urp','ugh'],
        '--fraggle' => sub { return ['rock','roll'] },
        '--person'  => \&Getopt::Complete::users, 
        '--output'  => \&Getopt::Complete::files, 
        '--exec'    => \&Getopt::Complete::commands, 
        ''          => \&Getopt::Complete::environment, 
        '--apple',
        '--ape',
        '--bear',
        'scott',
        'smith',
        'more'      =>  [
                            'stuff'     =>  [qw/11 22 33/],
                            'deeper'    =>  [
                                                'pot' => [qw/aa bb cc/],
                                                'of'  => [qw/dd ee ff/],
                                            ],
                        ]
;


1;
