#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Complete
        '--frog'    => ['ribbit','urp','ugh'],
        '--fraggle' => sub { return ['rock','roll'] },
        '--person'  => \&Getopt::Complete::users, 
        '--output'  => \&Getopt::Complete::files, 
        '--exec'    => \&Getopt::Complete::commands, 
        ''          => \&Getopt::Complete::environment, 
        '--apple'   => [],
        '--ape'     => '',
        '--bear'    => '',
        'scott'     => [],
        'smith'     => [],
;


1;
